// <auto-generated />
namespace QuanLyNhanSu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddIdToKhenThuongs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddIdToKhenThuongs));
        
        string IMigrationMetadata.Id
        {
            get { return "202411180918065_AddIdToKhenThuongs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
