//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSwap
    {
        public int Id { get; set; }
        public string MaHopDong { get; set; }
        public string TenKhachHang { get; set; }
        public string SdtKhachHang { get; set; }
        public string DiaChiKH { get; set; }
        public string KhuVuc { get; set; }
        public string MaNVLenPhieu { get; set; }
        public string MaNVTrienKhai { get; set; }
        public int SdtSale { get; set; }
        public string SaleNote { get; set; }
        public string PhiDichVu { get; set; }
        public System.DateTime ThoiGianNhanCa { get; set; }
        public Nullable<System.DateTime> ThoiGianHoanTat { get; set; }
        public Nullable<int> DanhGia { get; set; }
        public int TrangThai { get; set; }
    }
}
