//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public int Id { get; set; }
        public string LoaiThongBao { get; set; }
        public Nullable<int> MaPhieu { get; set; }
        public string TieuDe { get; set; }
        public string MaNVGuiTB { get; set; }
        public System.DateTime ThoiGianGuiTB { get; set; }
        public string MaNVNhanTB { get; set; }
        public Nullable<System.DateTime> ThoiGianDuyetTB { get; set; }
        public int TrangThai { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
    }
}
