//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VatTuCaNhan
    {
        public int Id { get; set; }
        public string MaNhanVien { get; set; }
        public string MaVatTu { get; set; }
        public int SoLuong { get; set; }
        public int TinhTrang { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual VatTu VatTu { get; set; }
    }
}
